bind=CTRL+SHIFT,TAB,killclient
bind=CTRL+SHIFT,r,reload_config
bind=CTRL+SHIFT,a,spawn,ghostty +new-window
bind=CTRL+SHIFT,f,spawn,rofi -show drun -theme ~/.config/rofi/apps.rasi
bind=ALT,period,focusdir,up
bind=ALT,comma,focusdir,down
bind=CTRL+SHIFT,1,view,1
bind=CTRL+SHIFT,2,view,2
bind=CTRL+SHIFT,3,view,3
bind=CTRL+SHIFT,4,view,4
bind=ALT,1,tag,1
bind=ALT,2,tag,2
bind=ALT,3,tag,3
bind=ALT,4,tag,4
mousebind=ALT,code:273,killclient
