bind=CTRL,TAB,killclient
bind=CTRL+SHIFT,r,reload_config
bind=CTRL,f,spawn,rofi -show drun -theme ~/.config/rofi/apps.rasi
bind=CTRL,a,spawn,ghostty +new-window
bind=ALT,period,viewtoright
bind=ALT,comma,viewtoleft
bind=ALT,slash,toggle_named_scratchpad,com.mitchellh.ghostty,file-manager,ghostty --title=file-manager +new-window -e yazi
bind=ALT,p,toggle_named_scratchpad,com.mitchellh.ghostty,cmd,ghostty --title=cmd +new-window
bind=ALT,backslash,toggle_named_scratchpad,com.mitchellh.ghostty,btop,ghostty --title=btop +new-window -e btop 
bind=ALT,1,toggle_named_scratchpad,com.mitchellh.ghostty,leetcode,ghostty --title=leetcode +new-window -e nvim leetcode.nvim
mousebind=ALT,code:273,killclient
