monitorrule=name:DP-1,width:2560,height:1440,refresh:120,x:0,y:0
exec-once=gammastep
exec-once=hypridle
exec-once=awww-daemon
exec-once=waypaper --restore
exec-once=qs
exec-once=ghostty +new-window
source=./bind.conf
source=./rules.conf
source=./style.conf
