monitorrule=name:DP-1,width:2560,height:1440,refresh:120,x:0,y:0,scale:1
exec-once=gammastep
exec-once=hypridle
exec-once=qs
exec-once=awww-daemon
exec-once=waypaper --restore
exec-once=ghostty +new-window
exec-once=ollama run qwen2.5-coder:7b
source=./bind.conf
source=./rules.conf
source=./style.conf
