tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile

windowrule=isfloating:1,width:1000,height:720,offsetx:-70,offsety:-95,appid:youtube-music-desktop-app
windowrule=isfloating:1,width:420,height:140,offsetx:99,offsety:-98,title:quickshell
windowrule=isfloating:1,width:400,height:500,offsetx:70,offsety:-85,appid:blueman-manager-wrapped
windowrule=isfloating:1,width:800,height:500,offsety:-85,appid:waypaper
windowrule=isfloating:1,width:700,height:500,appid:io.mgba.mGBA

windowrule=isfloating:1,offsetx:-80,offsety:60,appid:droidcam
windowrule=isfloating:1,width:700,height:500,title:.*File.*
windowrule=isfloating:1,width:700,height:500,title:.*Save.*
windowrule=isfloating:1,width:700,height:700,title:Polychromatic
windowrule=isfloating:1,width:1000,height:720,title:Video Trimmer

windowrule=isfloating:1,width:1280,height:720,offsetx:-20,offsety:-50,appid:steam,title:Steam
windowrule=isfloating:1,appid:steam

windowrule=isnamedscratchpad:1,width:1280,height:800,title:file-manager
windowrule=isnamedscratchpad:1,width:1280,height:800,title:cmd
windowrule=isnamedscratchpad:1,width:1280,height:800,title:btop
