borderpx=0
gappoh=50
gappov=20
unfocused_opacity=0.6
focused_opacity=0.95
blur=1
sloppyfocus=0

animation_type_open=slide
animation_type_close=fade
animation_duration_move=300
animation_duration_focus=100
animation_duration_tag=200
animation_duration_open=250
animation_duration_close=150
