################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-1, 2560x1440@100, 0x0, 1

#################
### VARIABLES ###
#################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$center = hyprctl dispatch workspace 2
$terminal =  ghostty
$warm = busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateTemperature n -2000

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = hyprpaper & waypaper --restore & wl-gammarelay-rs & qs
exec-once = xhost +SI:localuser:root
exec-once = $center & $terminal

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = XDG_CURRENT_DESKTOP,Hyprland

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

#############
### INPUT ###
#############

input {
    kb_layout = us

    follow_mouse = 2

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

source=rules.conf
source=keybinds.conf
source=style.conf
