################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = HDMI-A-1, 2560x1440@144, 0x0, 1

#################
### VARIABLES ###
#################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty 
$menu = rofi -show run -theme ~/.config/rofi/config.rasi 
$fileManager = nemo
$web = firefox
$startup = hyprctl dispatch workspace 2
$border = c8a3f2aa


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $startup & $terminal 
exec-once = xhost +SI:localuser:root
exec-once = swww & waypaper --restore & nm-applet --indicator & hypridle & wl-gammarelay-rs & waybar & mako

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = XDG_CURRENT_DESKTOP,Hyprland

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

source=rules.conf
source=keybinds.conf
source=style.conf
