###################
### KEYBINDINGS ###
###################

$mainMod = CTRL_SHIFT # Sets "Windows" key as main modifier
$menu = rofi -show drun -theme ~/.config/rofi/apps.rasi 

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, F, exec, $menu
bind = $mainMod, A, exec, $terminal
bind = $mainMod, TAB, killactive,

# Toggle Waybar
bind = $mainMod, R, exec, toggle_bar 

bind = ALT, period, movefocus, u 
bind = ALT, comma, movefocus, d 

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = ALT, 1, movetoworkspace, 1
bind = ALT, 2, movetoworkspace, 2
bind = ALT, 3, movetoworkspace, 3
bind = ALT, 4, movetoworkspace, 4
bind = ALT, 5, movetoworkspace, 5
bind = ALT, 6, movetoworkspace, 6
bind = ALT, 7, movetoworkspace, 7
bind = ALT, 8, movetoworkspace, 8
bind = ALT, 9, movetoworkspace, 9
bind = ALT, 0, movetoworkspace, 10

# Color temp control (Night light)
bind= $mainMod ,Up,exec,busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateTemperature n -500
bind= $mainMod ,Down,exec,busctl --user -- call rs.wl-gammarelay / rs.wl.gammarelay UpdateTemperature n +500 

# Move/resize windows with mainMod + LMB/RMB and dragging
binds {
    drag_threshold = 10  # Fire a drag event only after dragging for more than 10px
}
bindm = ALT, mouse:272, movewindow
bind = ALT, mouse:273, killactive
bind = ALT, mouse_up, togglefloating
