##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# windowrule = float true, center true, size 700 500, match:title ^(blueman)$

windowrule = float true, center true, size 850 500, match:class waypaper

windowrule = float true, center true, size 700 500, match:class nemo

windowrule = float true, center true, size 700 500, match:title mGBA

windowrule = float true, center true, size 700 500, match:class .blueman-manager-wrapped

windowrule = float true, center true, size 1000 720, match:class YouTube Music Desktop App

windowrule = float true, center true, size 700 500, match:class io.mgba.mGBA

windowrule = float true, center true, size 700 500, match:class org.pulseaudio.pavucontrol

windowrule = float true, center true, size 700 700, match:title Polychromatic

windowrule = float true, center true, size 1280 720, match:title Steam

windowrule = float true, center true, size 1280 720, match:title Celeste

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
