##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

windowrule = float true, center true, no_initial_focus true, match:class .*ueberzugpp_.*

windowrule = float true, center true, size 850 500, match:class waypaper

windowrule = float true, center true, size 700 500, match:class nemo

windowrule = float true, center true, size 700 500, match:title mGBA

windowrule = float true, center true, size 700 500, match:class .blueman-manager-wrapped

windowrule = float true, center true, size 1000 720, match:class YouTube Music Desktop App

windowrule = float true, center true, size 700 500, match:class io.mgba.mGBA

windowrule = float true, center true, size 700 500, match:class org.pulseaudio.pavucontrol

windowrule = fullscreen true, match:class osu!

windowrule = float true, center true, size 700 700, match:title Polychromatic

windowrule = float true, center true, size 700 500, match:title Picture-in-Picture

windowrule = float true, center true, size 1280 720, match:title Steam, match:class steam 

windowrule = float true, center true, size 1280 720, match:title Steam Settings, match:class steam

windowrule = float true, match:class steam 

windowrule = float true, center true, match:title Celeste

windowrule = float true, center true, size 700 500, match:title .*File.*

windowrule = workspace 3, match:class steam
# windowrule = workspace 1, match:class firefox

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
