##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

windowrule = float true, center true, size 700 500,  move 60 60, match:class nemo

windowrule = float true, center true, size 1000 720, move 300 100, match:class electron

windowrule = float true, center true, size 850 500,  move 855 160, match:class waypaper

windowrule = float true, center true, size 700 500,  move 1750 220, match:class .blueman-manager-wrapped

windowrule = float true, center true, size 700 500, match:class io.mgba.mGBA

windowrule = float true, center true, size 700 500, match:class org.pulseaudio.pavucontrol

windowrule = match:initial_title Ghostty

windowrule = float true, center false, size 2000 1380, move 100 50, match:initial_class firefox 

windowrule = float true, center true, size 700 700, match:title Polychromatic

windowrule = float true, center true, size 700 500, match:title Picture-in-Picture

windowrule = float true, center true, size 1280 720, move 600 300, match:title Steam 

windowrule = float true, center true, size 1280 720, match:title Steam Settings

windowrule = float true, match:class steam 

windowrule = float true, center true, size 700 500, match:title .*File.*

windowrule = float true, center true, size 700 500, match:title .*Save.*

windowrule = float true, center false, size 420 140, move 2115 65, match:title quickshell

# layerrule = blur on, match:namespace quickshell

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
