[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "p" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = "e"
run = "shell --block --interactive"

[[mgr.prepend_keymap]]
desc = "copy file path"
on = ["f", "p"]
run = "copy path"

[[mgr.prepend_keymap]]
desc = "copy filename"
on = ["f", "n"]
run = "copy filename"

[[mgr.prepend_keymap]]
desc = "copy filename without extension"
on = ["f", "e"]
run = "copy name_without_ext"
