[mgr]
linemode = "none"
ratio = [1, 1, 1]
show_hidden = true
show_symlink = true
sort_by = "extension"
sort_dir_first = true
sort_reverse = false
sort_sensitive = true

[[opener.edit]]
block = true
run = "nvim \"$@\""

[preview]
image_filter = "lanczos3"
image_quality = 90
max_height = 900
max_width = 600
tab_size = 1

[tasks]
bizarre_retry = 5
macro_workers = 10
micro_workers = 5
