[window]
opacity = 1 

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

[font]
size = 10.0

[font.normal]
family = "GohuFont 14 Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

# [colors.primary]
# background = '#16181a'
# foreground = '#08bdba'
#
# # Normal colors
# [colors.normal]
# black   = '#16181a'
# red     = '#f07178'
# green   = '#ff7eb6'
# yellow  = '#c3e88d'
# blue    = '#82cfff'
# magenta = '#c792ea'
# cyan    = '#60adec'
# white   = '#08bdba'

# Gruvbox
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
