{ config, lib, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    neovim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    nodejs_24
    swww
    blender
    wireshark
    stow
    rofi
    nemo
    fastfetch
    unzip
    swaynotificationcenter
    waybar
    waypaper
    hypridle
    hyprpicker
    gtk3
    gtk4
    yazi
    tmux
    wl-clipboard
    poppler
    fd
    ripgrep
    fzf
    zoxide
    alacritty
    wl-gammarelay-rs
    wl-gammarelay-applet
    git
    ytmdesktop
    uwsm
    networkmanagerapplet
    blueman
    dconf-editor
    ueberzugpp
    xhost
  ];
}
