#!/usr/bin/env bash

chosen=$(printf "  Power Off\n Restart\n  Suspend\n  Log Out" | rofi -dmenu -i -theme ~/.config/rofi/power.rasi)

case "$chosen" in
	"  Power Off") shutdown now ;;
	" Restart") systemctl reboot --firmware ;;
	"  Suspend") systemctl suspend ;;
	"  Log Out") hyprctl dispatch exit ;;
	*) exit 1 ;;
esac
