#!/usr/bin/env bash
tmp=$(hyprpicker)
if [ -n "$tmp" ]; then
    echo "@define-color background #16181a;
@define-color foreground #d3d3d3;
@define-color color7 #d3d3d3;
@define-color color9 $tmp;" >> tmp.txt
    mv tmp.txt ~/.themes/waybar.css
fi
