#!/bin/bash
hyprctl hyprpaper reload HDMI-A-1,"~/.wallpapers/$1" 
cd ~/.cache/wallpaper 
rm -r * 
cp ~/.wallpapers/$1 .
echo "unload
preload = ~/.cache/wallpaper/$1
wallpaper = HDMI-A-1, ~/.cache/wallpaper/$1" > ~/.config/hypr/hyprpaper.conf
